### ISSUE TITLE
issue: dimension should be `sonde_id` (?)

### ISSUE THREAD

**Issue by d70-t** [Geet-George/JOANNE#51] opened 2021-03-15 14:17 UTC
This might be related to #34 and #48 .

I think the dimension along soundings should be `sonde_id` or whatever the name of the variable containing the sonde-id is. In v0.9.2 the dimension is `sounding`.

The effect of this change will be that selecting soundings by the (only real) unique identifier will become a lot easier (i.e. `ds.sel(sonde_id="<sonde_id>"))` or `ds.sel(sonde_id=[list, of, sonde_ids])`.

**Comment by Geet-George** [comment] 2021-03-15 14:25
Great timing!! I am implementing exactly that.. But first introducing `sonde_id` a bit earlier. First in Level-2, and then it propagates further. Initially, the `sonde_id` sequencing was based on time from the filename. Usually this is okay, but for the 40 odd sondes where the launch time is different from filename time, this messes up the sequence. So, first sorting that out and then, yes, `sonde_id` will be dimension for L3 & L4. 

For #34 and #48, the issue is that currently the flight-phase-segmentation (FPS) files and JOANNE files are out of sync, so there are some sondes that don't agree between them. This is because of the new QC in JOANNE's later versions, after the FPS files were created. I will start a new issue for this in the FPS repo. Till this issue is sorted, I cannot run Level-4 scripts in their current form, which is okay except for the out-of-sync input files.

**Comment by Geet-George** [comment] 2021-03-15 14:27
Note that #34 is already closed.

**Comment by d70-t** [comment] 2021-03-15 14:28
I must admit that I just skimmed over the two referenced issues...

**Comment by Geet-George** [comment] 2021-03-15 14:30
No worries.. I haven't made it very clear in the issues that the problem is with the sync between FPS and JOANNE.

**Comment by Geet-George** [comment] 2021-04-15 10:10
[This commit](https://github.com/Geet-George/JOANNE/commit/c304e4039963791db3b3b5e80ef21697fb0ad7a0) solves this issue, therefore closing this.

**Closed by Geet-George** 2021-04-15 10:10 UTC
